package KieRule;
import com.admission.drools.api.model.Learner;

rule "Product Engineering Course"

when
learnerObject : Learner(hscPercentage>75 && sscPercentage>75 && graduationPercentage>70 && isEntryExamCleared());
then
learnerObject.setCourseEnrolled("Product Engineering Course");
end;

rule "Software Engineering Course"

when
learnerObject : Learner(hscPercentage>75 && sscPercentage>75 && graduationPercentage>70 && !isEntryExamCleared());
then
learnerObject.setCourseEnrolled("Software Engineering Course");
end;