package KieRule;
import java.util.Map;

rule "Outstanding"
when
    $map: Map((this["marks"] > 90) && (this["marks"] <= 100))
then
    $map.put("interpretation","Outstanding");
end

rule "Excellent"
when
    $map: Map((this["marks"] > 80) && (this["marks"] < 89))
then
    $map.put("interpretation","Excellent");
end

rule "Very Good"
when
    $map: Map((this["marks"] > 70) && (this["marks"] < 79))
then
    $map.put("interpretation","Very Good");
end

rule "Good"
when
    $map: Map((this["marks"] > 60) && (this["marks"] < 69))
then
    $map.put("interpretation","Good");
end

rule "Fair"
when
    $map: Map((this["marks"] > 50) && (this["marks"] < 59))
then
    $map.put("interpretation","Fair");
end

rule "Failed"
when
    $map: Map((this["marks"] <= 50))
then
    $map.put("interpretation","Failed");
end