package KieRule;
import com.admission.drools.api.model.GradeManager;

rule "Outstanding"

when
learnerObject : GradeManager((orgName.equalsIgnoreCase("IBM")) && (marksObtained>=91 && marksObtained<=100));
then
learnerObject.setInterpretation("Outstanding");
learnerObject.setGrade("A");
end;

rule "Excellent"

when
learnerObject : GradeManager((orgName.equalsIgnoreCase("IBM")) && (marksObtained>=81 && marksObtained<=90.99));
then
learnerObject.setInterpretation("Excellent");
learnerObject.setGrade("B");
end;

rule "Good"

when
learnerObject : GradeManager((orgName.equalsIgnoreCase("IBM")) && (marksObtained>=71 && marksObtained<=80.99));
then
learnerObject.setInterpretation("Good");
learnerObject.setGrade("C");
end;

rule "Fair"

when
learnerObject : GradeManager((orgName.equalsIgnoreCase("IBM")) && (marksObtained>=50 && marksObtained<=70.99));
then
learnerObject.setInterpretation("Fair");
learnerObject.setGrade("D");
end;

rule "Poor"

when
learnerObject : GradeManager((orgName.equalsIgnoreCase("IBM")) && (marksObtained<50 ));
then
learnerObject.setInterpretation("Poor");
learnerObject.setGrade("E");
end;

rule "NIIT_Outstanding"

when
learnerObject : GradeManager((orgName.equalsIgnoreCase("NIIT")) && (marksObtained>=85 && marksObtained<=100));
then
learnerObject.setInterpretation("Outstanding");
learnerObject.setGrade("A");
end;

rule "NIIT_Excellent"

when
learnerObject : GradeManager((orgName.equalsIgnoreCase("NIIT")) && (marksObtained>=75 && marksObtained<=84.99));
then
learnerObject.setInterpretation("Excellent");
learnerObject.setGrade("B");
end;

rule "NIIT_Good"

when
learnerObject : GradeManager((orgName.equalsIgnoreCase("NIIT")) && (marksObtained>=65 && marksObtained<=74.99));
then
learnerObject.setInterpretation("Good");
learnerObject.setGrade("C");
end;

rule "NIIT_Fair"

when
learnerObject : GradeManager((orgName.equalsIgnoreCase("NIIT")) && (marksObtained>=50 && marksObtained<=64.99));
then
learnerObject.setInterpretation("Fair");
learnerObject.setGrade("D");
end;

rule "NIIT_Poor"

when
learnerObject : GradeManager((orgName.equalsIgnoreCase("NIIT")) && (marksObtained<50 ));
then
learnerObject.setInterpretation("Poor");
learnerObject.setGrade("E");
end;
